FROM ubuntu:jammy AS builder

WORKDIR /download_utils

COPY /download_utils /download_utils 

RUN apt-get update && \
    apt-get install -y \
	python3 \
	python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir -r /download_utils/requirements.txt && \
    pyinstaller -F /download_utils/main.py

FROM azul/zulu-openjdk:17

WORKDIR /minecraft

COPY --from=builder /download_utils/dist/main /utils/download_utils/dist/main

RUN apt-get update && \
	apt-get install -y \
	fontconfig \
	unzip && \
	rm -rf /var/lib/apt/lists/*

COPY server.properties /tmp/server.properties
COPY eula.txt /tmp/eula.txt

COPY entrypoint.sh /utils/entrypoint.sh
COPY setup_properties.sh /utils/setup_properties.sh
COPY start_server.sh /utils/start_server.sh
COPY Log4jPatcher-1.0.1.jar /utils/Log4jPatcher.jar

RUN chmod +x \
    /utils/entrypoint.sh \
    /utils/setup_properties.sh \
    /utils/start_server.sh \
    /utils/download_utils/dist/main

ENV ENABLE_LOG4J_PATCH=true
ENV JVM_OPTS="-Xmx4098M -Xms4098M"

ENTRYPOINT ["/utils/entrypoint.sh"]