FROM ubuntu:jammy AS builder

WORKDIR /download_utils

COPY /download_utils /download_utils 

RUN apt-get update && \
    apt-get install -y \
	python3 \
	python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir -r requirements.txt && \
    pyinstaller -F main.py

FROM azul/zulu-openjdk:11

RUN apt-get update && \
	apt-get install -y \
	fontconfig && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /minecraft

COPY resources/eula.txt /tmp/eula.txt
COPY resources/server.properties /tmp/server.properties

COPY --from=builder /download_utils/dist/main /bin/main

COPY /scripts /scripts

RUN chmod +x \
    /scripts/start_server.sh \
    /bin/main

ENV ENABLE_LOG4J_PATCH=true
ENV JVM_OPTS="-Xmx4098M -Xms4098M"

ENTRYPOINT ["/scripts/start_server.sh"]