services:
  minecraft:
    image: ivantopgaming/minecraft_server:graalvm-24
    container_name: survival
    ports:
      - "25565:25565"
    volumes:
      - ./server:/minecraft
    environment:
      - JVM_OPTS=-Xmx4G -Xms4G
      - CORE_JAR=server.jar
      - DIFFICULTY=hard
      - ALLOW_NETHER=false
      - MOTD=Waiting for players...
      - ONLINE_MODE=false
      - GAME_VERSION=1.21.8
      - CORE_TYPE=leaf
      - ENABLE_LOG4J_PATCH=true
      - ENABLE_API=true
    restart: unless-stopped
    stop_grace_period: 120s
    stdin_open: true
    tty: true