FROM ubuntu:jammy AS builder

WORKDIR /app

COPY download_utils download_utils/
COPY api api/

RUN apt update && \
    apt install -y --fix-missing \
	binutils\
	python3 \
	python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir -r /app/download_utils/requirements.txt	
RUN pip3 install --no-cache-dir -r /app/api/requirements.txt
	
WORKDIR /app/download_utils
RUN pyinstaller -F /app/download_utils/main.py

WORKDIR /app/api
RUN pyinstaller -F /app/api/main.py

FROM azul/zulu-openjdk:11

RUN apt update && \
	apt install -y --fix-missing curl fontconfig && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /minecraft

COPY resources/eula.txt /tmp/eula.txt
COPY resources/server.properties /tmp/server.properties

COPY --from=builder /app/download_utils/dist/main /bin/download_utils
COPY --from=builder /app/api/dist/main /bin/api

COPY /scripts /scripts

RUN chmod +x \
    /scripts/start_server.sh \
    /bin/download_utils \
	/bin/api

ENV ENABLE_LOG4J_PATCH=true
ENV JVM_OPTS="-Xmx4098M -Xms4098M"

ENTRYPOINT ["/scripts/start_server.sh"]