#!/bin/bash

PROPERTIES_FILE="/minecraft/server.properties"

cp /tmp/server.properties "${PROPERTIES_FILE}"

update_property() {
    local key="$1"
    local value="$2"
    sed -i "s/^${key}=.*/${key}=${value}/" "${PROPERTIES_FILE}" || echo "${key}=${value}" >> "${PROPERTIES_FILE}"
}

# Жоский маппинг
declare -A ENV_MAPPING=(
    ["ACCEPTS_TRANSFERS"]="accepts-transfers"
    ["ALLOW_FLIGHT"]="allow-flight"
    ["ALLOW_NETHER"]="allow-nether"
    ["BROADCAST_CONSOLE_TO_OPS"]="broadcast-console-to-ops"
    ["BROADCAST_RCON_TO_OPS"]="broadcast-rcon-to-ops"
    ["BUG_REPORT_LINK"]="bug-report-link"
    ["DEBUG"]="debug"
    ["DIFFICULTY"]="difficulty"
    ["ENABLE_COMMAND_BLOCK"]="enable-command-block"
    ["ENABLE_JMX_MONITORING"]="enable-jmx-monitoring"
    ["ENABLE_QUERY"]="enable-query"
    ["ENABLE_RCON"]="enable-rcon"
    ["ENABLE_STATUS"]="enable-status"
    ["ENFORCE_SECURE_PROFILE"]="enforce-secure-profile"
    ["ENFORCE_WHITELIST"]="enforce-whitelist"
    ["ENTITY_BROADCAST_RANGE"]="entity-broadcast-range-percentage"
    ["FORCE_GAMEMODE"]="force-gamemode"
    ["FUNCTION_PERMISSION_LEVEL"]="function-permission-level"
    ["GAMEMODE"]="gamemode"
    ["GENERATE_STRUCTURES"]="generate-structures"
    ["GENERATOR_SETTINGS"]="generator-settings"
    ["HARDCORE"]="hardcore"
    ["HIDE_ONLINE_PLAYERS"]="hide-online-players"
    ["INITIAL_DISABLED_PACKS"]="initial-disabled-packs"
    ["INITIAL_ENABLED_PACKS"]="initial-enabled-packs"
    ["LEVEL_NAME"]="level-name"
    ["LEVEL_SEED"]="level-seed"
    ["LEVEL_TYPE"]="level-type"
    ["LOG_IPS"]="log-ips"
    ["MAX_CHAINED_UPDATES"]="max-chained-neighbor-updates"
    ["MAX_PLAYERS"]="max-players"
    ["MAX_TICK_TIME"]="max-tick-time"
    ["MAX_WORLD_SIZE"]="max-world-size"
    ["MOTD"]="motd"
    ["NETWORK_COMPRESSION"]="network-compression-threshold"
    ["ONLINE_MODE"]="online-mode"
    ["OP_PERMISSION_LEVEL"]="op-permission-level"
    ["PAUSE_WHEN_EMPTY"]="pause-when-empty-seconds"
    ["PLAYER_IDLE_TIMEOUT"]="player-idle-timeout"
    ["PREVENT_PROXY_CONNECTIONS"]="prevent-proxy-connections"
    ["PVP"]="pvp"
    ["QUERY_PORT"]="query.port"
    ["RATE_LIMIT"]="rate-limit"
    ["RCON_PASSWORD"]="rcon.password"
    ["RCON_PORT"]="rcon.port"
    ["REGION_COMPRESSION"]="region-file-compression"
    ["REQUIRE_RESOURCE_PACK"]="require-resource-pack"
    ["RESOURCE_PACK"]="resource-pack"
    ["RESOURCE_PACK_ID"]="resource-pack-id"
    ["RESOURCE_PACK_PROMPT"]="resource-pack-prompt"
    ["RESOURCE_PACK_SHA1"]="resource-pack-sha1"
    ["SERVER_IP"]="server-ip"
    ["SERVER_NAME"]="server-name"
    ["SERVER_PORT"]="server-port"
    ["SIMULATION_DISTANCE"]="simulation-distance"
    ["SPAWN_MONSTERS"]="spawn-monsters"
    ["SPAWN_PROTECTION"]="spawn-protection"
    ["SYNC_CHUNK_WRITES"]="sync-chunk-writes"
    ["TEXT_FILTERING_CONFIG"]="text-filtering-config"
    ["TEXT_FILTERING_VERSION"]="text-filtering-version"
    ["USE_NATIVE_TRANSPORT"]="use-native-transport"
    ["VIEW_DISTANCE"]="view-distance"
    ["WHITE_LIST"]="white-list"
)

for env_var in "${!ENV_MAPPING[@]}"; do
    prop="${ENV_MAPPING[$env_var]}"
    value="${!env_var}"
    [ -n "$value" ] && update_property "$prop" "$value"
done